var questions = [{
    "question": 'The first mechanical computer designed by Charles Babbage was called?',
	"option1": 'Abacus',
	"option2":' Analytical Engine',
	"option3":'Calculator',
	"option4":' Processor',
	"answer": 2,    
},{
    "question": 'To which object does the location property belong?',
	"option1": 'Window',
	"option2": 'Position',
	"option3" :'Element',
    "option4": 'Location',
    "answer": 1
},{
    "question": 'What is the result of the following code snippet? window.location === document.location',
	"option1": 'False',
	"option2": 'True',
	"option3": '1',
    "option4": '0',
    "answer": 2,
},{
    "question": 'Which of the following is not a framework?',
	"option1": 'jQuery',
	"option2": '.NET',
	"option3": 'JavaScript',
    "option4": 'None of the mentioned',
    "answer": 3,
}, {
    "question": 'Inside which HTML element do we put the JavaScript?',
	"option1": '<javascript>',
	"option2": '<script>',
	"option3": '<scripting>',
    "option4": '<js>',
    "answer": 2,
}, {
    "question": 'Which of the following is the most powerful type of computer ?',
	"option1": 'Super-micro',
	"option2": 'Super conductor',
	"option3": 'Super computer',
    "option4": 'Megaframe',    
    "answer": 3,
},{
    "question": 'What is the correct syntax for referring to an external script called "script.js"?',
	"option1": '<script src="script.js">',
	"option2": '<script href="script.js">',
	"option3": '<script href="script.js">',
    "option4": '<script link="script.js">',
    "answer": 1,
},{
    "question": 'How do you write "Hello World" in an alert box?',
	"option1": 'alert("Hello World");',
	"option2": 'msgBox("Hello World");',
	"option3": 'prompt("Hello World");',
    "option4": 'alertBox("Hello World");',
    "answer": 1
}, {
    "question": 'How do you create a function in JavaScript?',
    "option1": 'function = myFunction()',
    "option2": 'function:myFunction()',
    "option3": 'function myFunction()',
    "option4": 'None of the mentioned',
    "answer": 3,
}, {
    "question": 'How do you call a function named "myFunction"?',
	"option1": 'myFunction()',
	"option2": 'call function myFunction()',
	"option3": 'call myFunction()',
    "option4": 'None of the mentioned',
    "answer": 1,
}]